--- #YAML:1.0
name:               Pod-Spelling
version:            0.7
abstract:           Send POD to a spelling checker
author:
    - Lee Goddard <lgoddard@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Pod::POM:       0.04
    Test::Builder:  0
    Test::Pod:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
